# Generated by Django 4.1.4 on 2023-01-10 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_alter_bookrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookrequest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bookrequestnotstock',
            options={},
        ),
        migrations.RemoveField(
            model_name='bookrequest',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='bookrequestnotstock',
            name='created_time',
        ),
    ]
