# Generated by Django 4.1.4 on 2023-01-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_alter_bookrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookrequest',
            options={'ordering': ['created_time']},
        ),
        migrations.AlterModelOptions(
            name='bookrequestnotstock',
            options={'ordering': ['created_time']},
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bookrequestnotstock',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
