# Generated by Django 4.1.4 on 2023-01-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_alter_bookrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='title',
            field=models.CharField(max_length=400, verbose_name='عنوان'),
        ),
    ]
