# Generated by Django 4.1.4 on 2023-01-11 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0008_alter_category_name_alter_category_slug_and_more'),
        ('comment', '0006_alter_bookrequest_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='author',
            field=models.CharField(max_length=300, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='توسط کاربر'),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='bookrequestnotstock',
            name='by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='توسط کاربر'),
        ),
        migrations.AlterField(
            model_name='bookrequestnotstock',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='bookrequestnotstock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='عنوان کتاب'),
        ),
    ]
